{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gradleup.shadow",
    "module": "shadow-gradle-plugin",
    "version": "9.0.0-beta15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "shadow-gradle-plugin-9.0.0-beta15.jar",
          "url": "shadow-gradle-plugin-9.0.0-beta15.jar",
          "size": 211418,
          "sha512": "c4f1a0a2986cd819240c5d63fce82ce2113573cf1ae15c22bdef7303fa73286ab3f13cf0c02277f7210a343d99224a5a144fc6710e5c9765e89dec41d6196ed9",
          "sha256": "fbf17c89d13462d6caa97616c7e6428d96e424fe20c669790dd35c4c961bc053",
          "sha1": "ac9c0a294c88ab3e1df63157fdda945981d20fe8",
          "md5": "3467b44b77612859fd7ba3facf57b638"
        }
      ],
      "capabilities": [
        {
          "group": "io.github.goooler.shadow",
          "name": "shadow-gradle-plugin",
          "version": "9.0.0-beta15"
        },
        {
          "group": "gradle.plugin.com.github.johnrengelman",
          "name": "shadow",
          "version": "9.0.0-beta15"
        },
        {
          "group": "com.github.jengelman.gradle.plugins",
          "name": "shadow",
          "version": "9.0.0-beta15"
        },
        {
          "group": "com.gradleup.shadow",
          "name": "shadow-gradle-plugin",
          "version": "9.0.0-beta15"
        },
        {
          "group": "gradle.plugin.com.github.jengelman.gradle.plugins",
          "name": "shadow",
          "version": "9.0.0-beta15"
        },
        {
          "group": "com.github.johnrengelman",
          "name": "shadow",
          "version": "9.0.0-beta15"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.apache.ant",
          "module": "ant",
          "version": {
            "requires": "1.10.15"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.19.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.24.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.vafer",
          "module": "jdependency",
          "version": {
            "requires": "2.12"
          }
        },
        {
          "group": "org.jdom",
          "module": "jdom2",
          "version": {
            "requires": "2.0.6.1"
          }
        },
        {
          "group": "org.codehaus.plexus",
          "module": "plexus-utils",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.codehaus.plexus",
          "module": "plexus-xml",
          "version": {
            "requires": "4.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "shadow-gradle-plugin-9.0.0-beta15.jar",
          "url": "shadow-gradle-plugin-9.0.0-beta15.jar",
          "size": 211418,
          "sha512": "c4f1a0a2986cd819240c5d63fce82ce2113573cf1ae15c22bdef7303fa73286ab3f13cf0c02277f7210a343d99224a5a144fc6710e5c9765e89dec41d6196ed9",
          "sha256": "fbf17c89d13462d6caa97616c7e6428d96e424fe20c669790dd35c4c961bc053",
          "sha1": "ac9c0a294c88ab3e1df63157fdda945981d20fe8",
          "md5": "3467b44b77612859fd7ba3facf57b638"
        }
      ],
      "capabilities": [
        {
          "group": "io.github.goooler.shadow",
          "name": "shadow-gradle-plugin",
          "version": "9.0.0-beta15"
        },
        {
          "group": "gradle.plugin.com.github.johnrengelman",
          "name": "shadow",
          "version": "9.0.0-beta15"
        },
        {
          "group": "com.github.jengelman.gradle.plugins",
          "name": "shadow",
          "version": "9.0.0-beta15"
        },
        {
          "group": "com.gradleup.shadow",
          "name": "shadow-gradle-plugin",
          "version": "9.0.0-beta15"
        },
        {
          "group": "gradle.plugin.com.github.jengelman.gradle.plugins",
          "name": "shadow",
          "version": "9.0.0-beta15"
        },
        {
          "group": "com.github.johnrengelman",
          "name": "shadow",
          "version": "9.0.0-beta15"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "shadow-gradle-plugin-9.0.0-beta15-javadoc.jar",
          "url": "shadow-gradle-plugin-9.0.0-beta15-javadoc.jar",
          "size": 261,
          "sha512": "97ecb9b486c0c54be4fef892ec4cf759720f2eff462083de2ac2550fd922fa825f59ac1cf854eb2604e9c227901d6a8d062a28915c694b8e73d6cc2d5a2548e9",
          "sha256": "c7e71f21bbfd57e89d017f02bf49fc3847f0d6613ccd199416ad868af8af2ae0",
          "sha1": "9315adb208a6e5635455fcd977b10e07a823d331",
          "md5": "1f0ef1768622847e30ddc8ba1b407424"
        }
      ],
      "capabilities": [
        {
          "group": "io.github.goooler.shadow",
          "name": "shadow-gradle-plugin",
          "version": "9.0.0-beta15"
        },
        {
          "group": "gradle.plugin.com.github.johnrengelman",
          "name": "shadow",
          "version": "9.0.0-beta15"
        },
        {
          "group": "com.github.jengelman.gradle.plugins",
          "name": "shadow",
          "version": "9.0.0-beta15"
        },
        {
          "group": "com.gradleup.shadow",
          "name": "shadow-gradle-plugin",
          "version": "9.0.0-beta15"
        },
        {
          "group": "gradle.plugin.com.github.jengelman.gradle.plugins",
          "name": "shadow",
          "version": "9.0.0-beta15"
        },
        {
          "group": "com.github.johnrengelman",
          "name": "shadow",
          "version": "9.0.0-beta15"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "shadow-gradle-plugin-9.0.0-beta15-sources.jar",
          "url": "shadow-gradle-plugin-9.0.0-beta15-sources.jar",
          "size": 59818,
          "sha512": "df271b476c67eccf85ef8ec53a746eae2cb00a4e573b016e54fad16b77caf702bcd939e25e16de4bdff740c93b1a21055380a9ee1587458ba6431c09942260d4",
          "sha256": "c2da8bb0a6c7fc85d7c7ec4707d7a00824aa7dfbf23084eeb71f58b5120b92eb",
          "sha1": "5ad429f07e815e0b0c5b864ad5619e3fa7087d38",
          "md5": "6f11561e8d4e595913cae182f5220f27"
        }
      ],
      "capabilities": [
        {
          "group": "io.github.goooler.shadow",
          "name": "shadow-gradle-plugin",
          "version": "9.0.0-beta15"
        },
        {
          "group": "gradle.plugin.com.github.johnrengelman",
          "name": "shadow",
          "version": "9.0.0-beta15"
        },
        {
          "group": "com.github.jengelman.gradle.plugins",
          "name": "shadow",
          "version": "9.0.0-beta15"
        },
        {
          "group": "com.gradleup.shadow",
          "name": "shadow-gradle-plugin",
          "version": "9.0.0-beta15"
        },
        {
          "group": "gradle.plugin.com.github.jengelman.gradle.plugins",
          "name": "shadow",
          "version": "9.0.0-beta15"
        },
        {
          "group": "com.github.johnrengelman",
          "name": "shadow",
          "version": "9.0.0-beta15"
        }
      ]
    }
  ]
}
